{
 "title": "gms_psql",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "User Location",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "valueName": "total",
   "targets": [
    {
     "rawSql": "select count(*) as value,c.\"GEOINTERNET\"  as metric,NOW() AS time from (\r\n\tselect  b.\"GEOINTERNET\",b.\"VALUE\",d.\"time\" as time,d.\"PARTYID\" from userlocation b left join \r\n(SELECT a.\"PARTYID\",MAX(a.\"TIMESTAMP\") as time from userlocation a  group by a.\"PARTYID\") d  \r\non b.\"TIMESTAMP\"= d.\"time\" where b.\"PARTYID\" = d.\"PARTYID\" and d.\"time\" >=  Now()::timestamp - INTERVAL '1 day' \r\n) c  group by c.\"GEOINTERNET\" "
    }
   ]
  },
  {
   "title": "User by application",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 0 },
   "targets": [
    {
     "rawSql": "  \r\n select count(*) as value, c.\"AREA\",  max(c.\"time\") as time from( \r\n  select b.\"AREA\",b.\"VALUE\",d.\"time\" as time,d.\"PARTYID\" from clickstream_active_sessions_mysql b  left join\r\n (select a.\"PARTYID\",MAX(a.\"TIMESTAMP\") as time from clickstream_active_sessions_mysql a group by a.\"PARTYID\") d\r\n  on b.\"TIMESTAMP\"= d.\"time\" where b.\"PARTYID\" = d.\"PARTYID\" and    $__timeFilter( time)\r\n ) c  group by c.\"AREA\" "
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select count(*) , now() as time\r\nfrom (SELECT MAX(b.\"TIMESTAMP\") as timestamp,b.\"PARTYID\" from clickstream_active_sessions_mysql b where $__timeFilter(b.\"TIMESTAMP\" )  group by b.\"PARTYID\") as c \r\n "
    }
   ]
  },
  {
   "title": "Device by user",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "select count(*) as value,c.\"DEVICE\" as metric, max(c.\"time\") as time from (\r\n\tselect  b.\"DEVICE\",b.\"VALUE\",d.\"time\" as time,d.\"PARTYID\" from useragent b left join \r\n(SELECT a.\"PARTYID\",MAX(a.\"TIMESTAMP\") as time from useragent a where   $__timeFilter( a.\"TIMESTAMP\") group by a.\"PARTYID\") d \r\non b.\"TIMESTAMP\"= d.\"time\" where b.\"PARTYID\" = d.\"PARTYID\" \r\n)  c  group by c.\"DEVICE\" "
    }
   ]
  },
  {
   "title": "Browser by user",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "select count(*) as value,c.\"BROWSER\" as metric, max(c.\"time\") as time from (\r\n\tselect  b.\"BROWSER\",b.\"VALUE\",d.\"time\" as time,d.\"PARTYID\" from useragent b left join \r\n(SELECT a.\"PARTYID\",MAX(a.\"TIMESTAMP\") as time from useragent a where   $__timeFilter( a.\"TIMESTAMP\") group by a.\"PARTYID\") d \r\non b.\"TIMESTAMP\"= d.\"time\" where b.\"PARTYID\" = d.\"PARTYID\" \r\n)  c  group by c.\"BROWSER\" "
    }
   ]
  },
  {
   "title": "OS by user",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "select count(*) as value,c.\"OS\" as metric, max(c.\"time\") as time from (\r\n\tselect  b.\"OS\",b.\"VALUE\",d.\"time\" as time,d.\"PARTYID\" from useragent b left join \r\n(SELECT a.\"PARTYID\",MAX(a.\"TIMESTAMP\") as time from useragent a where   $__timeFilter(a.\"TIMESTAMP\")  group by a.\"PARTYID\") d \r\non b.\"TIMESTAMP\"= d.\"time\" where b.\"PARTYID\" = d.\"PARTYID\" \r\n)  c  group by c.\"OS\" "
    }
   ]
  },
  {
   "title": "Browser version",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 17 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "select count(*) as value,c.\"USERAGENTNAME\" as metric, max(c.\"time\") as time from (\r\n\tselect  b.\"USERAGENTNAME\",b.\"VALUE\",d.\"time\" as time,d.\"PARTYID\" from browserversion b left join \r\n(SELECT a.\"PARTYID\",MAX(a.\"TIMESTAMP\") as time from browserversion a where   $__timeFilter( a.\"TIMESTAMP\") group by a.\"PARTYID\") d \r\non b.\"TIMESTAMP\"= d.\"time\" where b.\"PARTYID\" = d.\"PARTYID\")  c  group by c.\"USERAGENTNAME\""
    }
   ]
  }
 ]
}